name: AvaotaOS-build-mesa
on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set +e
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Set id
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
      - name: Build
        shell: bash
        run: |
          sudo bash build.sh
      - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.SY_PAT }}
            branch: jammy-devel
            directory: mesa-repo
            force: true
